import { CARD_H, CARD_W, NOTE_H, NOTE_W, SHAPE_H, SHAPE_W, type Scene } from '../demos/scene-types'

/** The hero canvas: an AI chat backend drawn step by step. */
export const HERO_SCENE: Scene = {
  width: 760,
  height: 500,
  nodes: [
    { id: 'client', type: 'frame', title: 'Клиент', x: 24, y: 20, w: 250, h: 210, step: 1 },
    {
      id: 'page',
      type: 'kind',
      kind: 'entry',
      title: 'Страница чата',
      subtitle: 'GET /chat',
      parentId: 'client',
      x: 65,
      y: 64,
      w: SHAPE_W,
      h: SHAPE_H,
      step: 2,
    },
    {
      id: 'api',
      type: 'kind',
      kind: 'api',
      title: 'POST /api/chat',
      subtitle: 'Hono · JWT в cookie',
      x: 300,
      y: 130,
      w: CARD_W,
      h: CARD_H,
      step: 3,
    },
    {
      id: 'agent',
      type: 'kind',
      kind: 'agent',
      title: 'Агент ответа',
      subtitle: 'streamText · maxSteps=5',
      status: 'doing',
      x: 300,
      y: 240,
      w: CARD_W,
      h: CARD_H,
      step: 5,
    },
    {
      id: 'db',
      type: 'kind',
      kind: 'store',
      title: 'PostgreSQL',
      subtitle: 'Prisma · history',
      status: 'done',
      x: 590,
      y: 16,
      w: SHAPE_W,
      h: SHAPE_H,
      step: 7,
    },
    {
      id: 'openai',
      type: 'kind',
      kind: 'external',
      title: 'OpenAI API',
      subtitle: 'gpt-4o',
      x: 590,
      y: 190,
      w: SHAPE_W,
      h: SHAPE_H,
      step: 9,
    },
    {
      id: 'queue',
      type: 'kind',
      kind: 'queue',
      title: 'Очередь задач',
      subtitle: 'BullMQ · Redis',
      x: 590,
      y: 356,
      w: SHAPE_W,
      h: SHAPE_H,
      step: 11,
    },
    {
      id: 'note',
      type: 'note',
      title: 'Проверить лимиты токенов',
      subtitle: 'до релиза · спросить у Али',
      x: 24,
      y: 300,
      w: NOTE_W,
      h: NOTE_H,
      step: 13,
    },
  ],
  edges: [
    { id: 'e1', source: 'page', target: 'api', label: 'запрос', step: 4 },
    { id: 'e2', source: 'api', target: 'agent', label: 'стрим', step: 6 },
    { id: 'e3', source: 'api', target: 'db', label: 'история', step: 8 },
    { id: 'e4', source: 'agent', target: 'openai', label: 'промпт', step: 10 },
    { id: 'e5', source: 'agent', target: 'queue', label: 'фоновая задача', step: 12 },
  ],
}

export const HERO_CURSOR_PATH = [
  { x: 560, y: 380 },
  { x: 250, y: 420 },
  { x: 460, y: 220 },
  { x: 700, y: 400 },
  { x: 150, y: 260 },
]
